import { AccountType } from '../../common/enums/account-type.enum';
import { CategoryType } from '../../common/enums/category-type.enum';
import { CreditType } from '../../common/enums/credit-type.enum';
import { FinancialSourceStatus } from '../../common/enums/financial-source-status.enum';
import { InstallmentStatus } from '../../common/enums/installment-status.enum';
import { PreferredLanguage } from '../../common/enums/preferred-language.enum';
import { ProviderType } from '../../common/enums/provider-type.enum';
import { TransactionType } from '../../common/enums/transaction-type.enum';

export const demoVerifiedUserSeed = {
  email: 'demo@dcredit.local',
  password: 'ChangeMe123!',
  fullName: 'Alex Rivera',
  emailVerified: true,
  preferredLanguage: PreferredLanguage.EN,
};

export const demoAdminUserSeed = {
  email: 'admin@dcredit.local',
  password: 'AdminAccess123!',
  fullName: 'Morgan Ops',
  emailVerified: true,
  preferredLanguage: PreferredLanguage.EN,
  isAdmin: true,
};

export const demoUnverifiedUserSeed = {
  email: 'pending@dcredit.local',
  password: 'VerifyMe123!',
  fullName: 'Jamie Torres',
  emailVerified: false,
  preferredLanguage: PreferredLanguage.ES,
};

export const activationJourneyUserSeeds = [
  {
    key: 'registered-only',
    email: 'registered.only@dcredit.local',
    password: 'ChangeMe123!',
    fullName: 'Taylor Registered',
    emailVerified: false,
    preferredLanguage: PreferredLanguage.EN,
    stage: 'registered',
  },
  {
    key: 'verified-only',
    email: 'verified.only@dcredit.local',
    password: 'ChangeMe123!',
    fullName: 'Riley Verified',
    emailVerified: true,
    preferredLanguage: PreferredLanguage.EN,
    stage: 'email_verified',
  },
  {
    key: 'source-connected',
    email: 'source.connected@dcredit.local',
    password: 'ChangeMe123!',
    fullName: 'Jordan Source',
    emailVerified: true,
    preferredLanguage: PreferredLanguage.ES,
    stage: 'source_connected',
  },
  {
    key: 'account-ready',
    email: 'account.ready@dcredit.local',
    password: 'ChangeMe123!',
    fullName: 'Casey Account',
    emailVerified: true,
    preferredLanguage: PreferredLanguage.EN,
    stage: 'account_ready',
  },
  {
    key: 'transaction-ready',
    email: 'transaction.ready@dcredit.local',
    password: 'ChangeMe123!',
    fullName: 'Avery Spend',
    emailVerified: true,
    preferredLanguage: PreferredLanguage.ES,
    stage: 'transaction_ready',
  },
  {
    key: 'credit-ready',
    email: 'credit.ready@dcredit.local',
    password: 'ChangeMe123!',
    fullName: 'Skyler Credit',
    emailVerified: true,
    preferredLanguage: PreferredLanguage.EN,
    stage: 'credit_ready',
  },
] as const;

export const demoUnverifiedVerificationTokenSeed = {
  token: 'demo-unverified-verification-token',
  expiresAt: new Date('2026-12-31T23:59:59.000Z'),
};

export const demoVerificationHistorySeeds = [
  {
    email: 'demo@dcredit.local',
    token: 'demo-verified-history-token',
    expiresAt: new Date('2026-02-20T12:00:00.000Z'),
    usedAt: new Date('2026-02-18T09:30:00.000Z'),
  },
  {
    email: 'admin@dcredit.local',
    token: 'demo-admin-history-token',
    expiresAt: new Date('2026-03-05T12:00:00.000Z'),
    usedAt: new Date('2026-03-03T16:45:00.000Z'),
  },
];

export const demoFinancialSourcesSeed = [
  {
    key: 'demo-bank',
    providerName: 'Demo Bank',
    providerType: ProviderType.BANK_API,
    status: FinancialSourceStatus.ACTIVE,
    credentialReference: 'vault://sources/demo-bank/alex-rivera',
  },
  {
    key: 'wallet-app',
    providerName: 'Pocket Wallet',
    providerType: ProviderType.MANUAL,
    status: FinancialSourceStatus.ACTIVE,
    credentialReference: 'vault://sources/pocket-wallet/alex-rivera',
  },
  {
    key: 'auto-finance',
    providerName: 'Auto Finance Co',
    providerType: ProviderType.CSV,
    status: FinancialSourceStatus.ACTIVE,
    credentialReference: 'vault://sources/auto-finance/alex-rivera',
  },
  {
    key: 'retail-sync',
    providerName: 'Retail Card Sync',
    providerType: ProviderType.OPEN_BANKING,
    status: FinancialSourceStatus.DISCONNECTED,
    credentialReference: 'vault://sources/retail-card-sync/alex-rivera',
  },
];

export const demoAccountsSeed = [
  {
    key: 'main-checking',
    sourceKey: 'demo-bank',
    accountName: 'Main Checking',
    accountType: AccountType.CHECKING,
    currency: 'USD',
    currentBalance: 2450.75,
    availableBalance: 2380.75,
  },
  {
    key: 'emergency-savings',
    sourceKey: 'demo-bank',
    accountName: 'Emergency Savings',
    accountType: AccountType.SAVINGS,
    currency: 'USD',
    currentBalance: 6800,
    availableBalance: 6800,
  },
  {
    key: 'digital-wallet',
    sourceKey: 'wallet-app',
    accountName: 'Digital Wallet',
    accountType: AccountType.WALLET,
    currency: 'USD',
    currentBalance: 420.25,
    availableBalance: 420.25,
  },
  {
    key: 'travel-card',
    sourceKey: 'demo-bank',
    accountName: 'Travel Rewards Card',
    accountType: AccountType.CREDIT_CARD,
    currency: 'USD',
    currentBalance: -1180.45,
    availableBalance: null,
  },
];

export const demoCategoriesSeed = [
  { key: 'salary', name: 'Salary', type: CategoryType.INCOME },
  { key: 'housing', name: 'Housing', type: CategoryType.EXPENSE },
  { key: 'groceries', name: 'Groceries', type: CategoryType.EXPENSE },
  { key: 'transport', name: 'Transport', type: CategoryType.EXPENSE },
  { key: 'utilities', name: 'Utilities', type: CategoryType.EXPENSE },
  { key: 'dining', name: 'Dining', type: CategoryType.EXPENSE },
  { key: 'healthcare', name: 'Healthcare', type: CategoryType.EXPENSE },
  { key: 'entertainment', name: 'Entertainment', type: CategoryType.EXPENSE },
  { key: 'credit-payment', name: 'Credit Payment', type: CategoryType.CREDIT_PAYMENT },
];

export const demoCreditsSeed = [
  {
    key: 'visa-platinum',
    sourceKey: 'demo-bank',
    name: 'Visa Platinum',
    creditType: CreditType.CREDIT_CARD,
    originalAmount: 7200,
    outstandingBalance: 3850.5,
    interestRate: 24.9,
    monthlyPayment: 230,
    nextPaymentDate: '2026-04-12',
    deferredPaymentDate: null,
    totalInstallments: null,
    remainingInstallments: null,
  },
  {
    key: 'auto-loan',
    sourceKey: 'auto-finance',
    name: 'Auto Loan',
    creditType: CreditType.AUTO_LOAN,
    originalAmount: 18500,
    outstandingBalance: 9240.4,
    interestRate: 11.25,
    monthlyPayment: 410,
    nextPaymentDate: '2026-04-18',
    deferredPaymentDate: null,
    totalInstallments: 48,
    remainingInstallments: 23,
  },
  {
    key: 'personal-loan',
    sourceKey: 'demo-bank',
    name: 'Personal Loan',
    creditType: CreditType.PERSONAL_LOAN,
    originalAmount: 4200,
    outstandingBalance: 2650.8,
    interestRate: 32.8,
    monthlyPayment: 185,
    nextPaymentDate: '2026-04-09',
    deferredPaymentDate: '2026-04-24',
    totalInstallments: 24,
    remainingInstallments: 14,
  },
];

export const demoInstallmentsSeed = [
  {
    creditKey: 'visa-platinum',
    installmentNumber: 1,
    dueDate: '2026-04-12',
    amount: 230,
    principalPortion: 148,
    interestPortion: 82,
    status: InstallmentStatus.PENDING,
  },
  {
    creditKey: 'visa-platinum',
    installmentNumber: 2,
    dueDate: '2026-05-12',
    amount: 230,
    principalPortion: 154,
    interestPortion: 76,
    status: InstallmentStatus.PENDING,
  },
  {
    creditKey: 'visa-platinum',
    installmentNumber: 3,
    dueDate: '2026-06-12',
    amount: 230,
    principalPortion: 161,
    interestPortion: 69,
    status: InstallmentStatus.PENDING,
  },
  {
    creditKey: 'auto-loan',
    installmentNumber: 24,
    dueDate: '2026-04-18',
    amount: 410,
    principalPortion: 315,
    interestPortion: 95,
    status: InstallmentStatus.PENDING,
  },
  {
    creditKey: 'auto-loan',
    installmentNumber: 25,
    dueDate: '2026-05-18',
    amount: 410,
    principalPortion: 322,
    interestPortion: 88,
    status: InstallmentStatus.PENDING,
  },
  {
    creditKey: 'auto-loan',
    installmentNumber: 26,
    dueDate: '2026-06-18',
    amount: 410,
    principalPortion: 329,
    interestPortion: 81,
    status: InstallmentStatus.PENDING,
  },
  {
    creditKey: 'personal-loan',
    installmentNumber: 11,
    dueDate: '2026-04-09',
    amount: 185,
    principalPortion: 109,
    interestPortion: 76,
    status: InstallmentStatus.DEFERRED,
  },
  {
    creditKey: 'personal-loan',
    installmentNumber: 12,
    dueDate: '2026-04-24',
    amount: 185,
    principalPortion: 113,
    interestPortion: 72,
    status: InstallmentStatus.PENDING,
  },
  {
    creditKey: 'personal-loan',
    installmentNumber: 13,
    dueDate: '2026-05-24',
    amount: 185,
    principalPortion: 117,
    interestPortion: 68,
    status: InstallmentStatus.PENDING,
  },
];

export const demoTransactionsSeed = [
  {
    accountKey: 'main-checking',
    date: new Date('2026-03-30T09:00:00.000Z'),
    description: 'Monthly Salary',
    amount: 5200,
    type: TransactionType.INCOME,
    merchant: 'Employer Inc.',
    categoryKey: 'salary',
  },
  {
    accountKey: 'main-checking',
    date: new Date('2026-03-31T13:10:00.000Z'),
    description: 'Rent Payment',
    amount: -1650,
    type: TransactionType.EXPENSE,
    merchant: 'Landlord LLC',
    categoryKey: 'housing',
  },
  {
    accountKey: 'main-checking',
    date: new Date('2026-04-01T18:20:00.000Z'),
    description: 'Weekly Groceries',
    amount: -132.42,
    type: TransactionType.EXPENSE,
    merchant: 'Fresh Market',
    categoryKey: 'groceries',
  },
  {
    accountKey: 'main-checking',
    date: new Date('2026-04-02T08:45:00.000Z'),
    description: 'Metro Card Reload',
    amount: -48.5,
    type: TransactionType.EXPENSE,
    merchant: 'City Transit',
    categoryKey: 'transport',
  },
  {
    accountKey: 'digital-wallet',
    date: new Date('2026-04-03T20:10:00.000Z'),
    description: 'Dinner with Friends',
    amount: -64.3,
    type: TransactionType.EXPENSE,
    merchant: 'Bistro 88',
    categoryKey: 'dining',
  },
  {
    accountKey: 'main-checking',
    date: new Date('2026-04-04T11:30:00.000Z'),
    description: 'Electricity Bill',
    amount: -118.2,
    type: TransactionType.EXPENSE,
    merchant: 'Power Grid',
    categoryKey: 'utilities',
  },
  {
    accountKey: 'main-checking',
    date: new Date('2026-04-06T16:05:00.000Z'),
    description: 'Pharmacy Purchase',
    amount: -38.75,
    type: TransactionType.EXPENSE,
    merchant: 'HealthPlus Pharmacy',
    categoryKey: 'healthcare',
  },
  {
    accountKey: 'main-checking',
    date: new Date('2026-04-07T21:15:00.000Z'),
    description: 'Streaming Bundle',
    amount: -19.99,
    type: TransactionType.EXPENSE,
    merchant: 'StreamCo',
    categoryKey: 'entertainment',
  },
  {
    accountKey: 'main-checking',
    creditKey: 'visa-platinum',
    date: new Date('2026-04-08T11:10:00.000Z'),
    description: 'Credit Card Payment',
    amount: -230,
    type: TransactionType.PAYMENT,
    merchant: 'Demo Bank',
    categoryKey: 'credit-payment',
  },
  {
    accountKey: 'main-checking',
    creditKey: 'personal-loan',
    date: new Date('2026-04-08T14:40:00.000Z'),
    description: 'Personal Loan Payment',
    amount: -185,
    type: TransactionType.PAYMENT,
    merchant: 'Demo Bank',
    categoryKey: 'credit-payment',
  },
];
